Java doc for matchlist
CSC207-2023Y-UofT/course-project-tindar pull request #103
Opened 2023-08-10 01:08 UTC by kresimirgotovac

Wrote java docs for all match list related parts. Please review for approval.

2023-08-10 01:13 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/matchlist/MatchListFragment.java
> + * for conversations */
*/ at the end in the next line pls

2023-08-10 01:17 UTC, kresimirgotovac commented on app/src/main/java/com/courseproject/tindar/ui/matchlist/MatchListFragment.java
> + * for conversations */
done

2023-08-10 01:25 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/matchlist/MatchListFragment.java
> + * for conversations */
That was quick :)

2023-08-10 01:43 UTC, jenniferjinyoungyang commented
Another, if you highlight class name, method name or class attribute name, and do 'option + Enter', it will have an option to add Javadoc. If you select that option, it will add blank javadoc at the top with pre-entered @param, @return etc.

2023-08-10 01:43 UTC, jenniferjinyoungyang requested changes

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/controllers/likelist/LikeListController.java
>  /** This controller class accepts user input and connects it to back-end likeList functions **/
This has to go up above the line of 'public class LikeListController {'

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/controllers/likelist/LikeListController.java
>      final LikeListInputBoundary userInput;
java doc for the class attribute too

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/controllers/likelist/LikeListController.java
> +     * @param userId the users match list we are returning
missing @return. it will complain if you are to generate javadoc.

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ds/DatabaseHelper.java
> +     * @param otherUserId user receiving a 'like' from userId
missing @return

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ds/DatabaseHelper.java
> +     * @param userId user who's match list we are retrieving
missing @return

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ds/DatabaseHelper.java
> +     * @param userIds users who's display names we are retrieving
missing @return

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListDsGateway.java
> +     * @return ArrayList<String[]> of userIds in the match list
having ArrayList<String[]> inside Javadoc throws error when generating javadoc

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListDsGateway.java
> +     * @return ArrayList<LikeListDsResponseModel> of display names in the match list
this line throws error when generating javadoc. you can do something like
![image](https://github.com/CSC207-2023Y-UofT/course-project-tindar/assets/76457965/a4e83398-5b51-4095-8506-564393c7019e)

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListDsResponseModel.java
>      private final String displayName;
javadoc for class attributes pls

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListDsResponseModel.java
> +     * Return userId
missing @return

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListDsResponseModel.java
> +     * Return users display name
missing @return

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListInteractor.java
> +     * @param userId id of user who we are retrieving the matched display names
missing @return

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListResponseModel.java
>      private final String[] displayNames;
javadoc for the class attributes pls

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListResponseModel.java
> +     * Return userIds in the users match list
missing @return

2023-08-10 01:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListResponseModel.java
> +     * Return users display names in the users match list
missing @return

2023-08-10 12:22 UTC, navarhontes commented
Flagging that there's some matchlist and like-list related stuff in DatabaseHelper that still needs JavaDocs. Making issue #106 and approving this PR.

2023-08-10 12:23 UTC, navarhontes submitted a review, later dismissed
Flagging that there's some matchlist and like-list related stuff in DatabaseHelper that still needs JavaDocs. Since there isn't any functionality change, I'm making issue https://github.com/CSC207-2023Y-UofT/course-project-tindar/issues/106 and approving this PR.

2023-08-11 00:41 UTC, jenniferjinyoungyang approved these changes

2023-08-11 02:14 UTC, jenniferjinyoungyang requested changes

2023-08-11 02:14 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListResponseModel.java
>      public String[] getDisplayNames() {
pls add quick description for the method

2023-08-11 02:14 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListResponseModel.java
>      public String[] getUserIds() {
pls add quick description for the method

2023-08-11 03:01 UTC, jenniferjinyoungyang approved these changes

2023-08-11 16:25 UTC, navarhontes commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListInteractor.java
>      private final LikeListDsGateway likeListDsGateway;
Javadoc

2023-08-11 16:25 UTC, navarhontes commented on app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListInteractor.java
>      public LikeListInteractor(LikeListDsGateway likeListDsGateway) {
Javadoc

2023-08-12 01:30 UTC, A-Bunch-Of-Atoms submitted a review, later dismissed
Seconding Sophia's requests for javadocs for class attributes.

2023-08-12 02:54 UTC, jenniferjinyoungyang submitted a review, later dismissed

2023-08-12 12:27 UTC, navarhontes submitted a review, later dismissed
Thanks for the addition. Made some minor edits to the PR description.

2023-08-12 14:35 UTC, candidcalcifer approved these changes

2023-08-12 14:43 UTC, jenniferjinyoungyang approved these changes

2023-08-12 14:46 UTC, navarhontes approved these changes
Re-approving; updates since last approval are just merge conflict resolutions.

2023-08-12 17:04 UTC, candidcalcifer approved these changes

2023-08-12 17:04 UTC, merged