View Profiles and User List Controller Test Cases
CSC207-2023Y-UofT/course-project-tindar pull request #108
Opened 2023-08-10 17:50 UTC by candidcalcifer

2023-08-12 01:26 UTC, A-Bunch-Of-Atoms approved these changes

2023-08-12 02:26 UTC, jenniferjinyoungyang commented on app/src/test/java/com/courseproject/tindar/controllers/userlist/UserListControllerUnitTest.java
> +public class UserListControllerUnitTest {
This isn't controller unit test. You need to input mockUserListUserInput as an argument when instantiating controller, and call the method in the controller.

2023-08-12 02:30 UTC, jenniferjinyoungyang requested changes

2023-08-12 02:30 UTC, jenniferjinyoungyang commented on app/src/test/java/com/courseproject/tindar/controllers/viewprofiles/ViewProfilesControllerUnitTest.java
> +public class ViewProfilesControllerUnitTest {
Again, you need to input mockUserListUserInput as an argument when instantiating controller, and call the method in the controller to unit test controller

2023-08-13 11:37 UTC, jenniferjinyoungyang commented
The controller tests are done together in https://github.com/CSC207-2023Y-UofT/course-project-tindar/pull/142

2023-08-13 11:37 UTC, closed without merging