BlankNavActivity javadocs
CSC207-2023Y-UofT/course-project-tindar pull request #111
Opened 2023-08-10 18:18 UTC by candidcalcifer

2023-08-12 01:23 UTC, A-Bunch-Of-Atoms submitted a review, later dismissed

2023-08-12 02:33 UTC, jenniferjinyoungyang requested changes

2023-08-12 02:33 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/BlankNavActivity.java
>  public class BlankNavActivity extends AppCompatActivity {
needs JavaDoc for the class

2023-08-12 02:33 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/BlankNavActivity.java
>      private AppBarConfiguration mAppBarConfiguration;
needs JavaDoc for the class attribute

2023-08-12 02:33 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/BlankNavActivity.java
> +     */
needs @param

2023-08-12 02:33 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/BlankNavActivity.java
> +     */
needs @param

2023-08-13 18:16 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/BlankNavActivity.java
> +     * @param menu collection of menu items associated with the activity
can you add @return here?

2023-08-13 20:21 UTC, jenniferjinyoungyang approved these changes

2023-08-13 20:23 UTC, yiwxng approved these changes

2023-08-13 20:31 UTC, kresimirgotovac approved these changes

2023-08-13 20:32 UTC, kresimirgotovac approved these changes

2023-08-13 20:33 UTC, merged