Design for settings change completed.
CSC207-2023Y-UofT/course-project-tindar pull request #114
Opened 2023-08-10 22:21 UTC by A-Bunch-Of-Atoms

2023-08-10 22:28 UTC, kresimirgotovac submitted a review, later dismissed

2023-08-10 22:28 UTC, candidcalcifer approved these changes, later dismissed

2023-08-12 01:45 UTC, jenniferjinyoungyang commented
Pls add JavaDoc for the class, class attributes, and methods

2023-08-12 01:49 UTC, jenniferjinyoungyang commented
Can you please show warnings 
- when no new email is inputted
- when no password is inputted

Can you also make the rule that the password to be at least 6 characters long? This is what is being used in the Sign-Up

2023-08-12 01:53 UTC, jenniferjinyoungyang commented
Also, pls add a description in this PR
- what you did
- why you did it
- implementation details

2023-08-12 02:43 UTC, jenniferjinyoungyang requested changes

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/ChangeEmailActivity.java
> +    // Button that sends user back to the settings screen.
JavaDoc should look like 
```
/**
* Button ....
*/
```

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/ChangeEmailActivity.java
> +public class ChangeEmailActivity extends AppCompatActivity {
needs JavaDoc above this to briefly describe what this class is doing

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/ChangeEmailActivity.java
> +     */
missing @param

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/ChangePasswordActivity.java
> +public class ChangePasswordActivity extends AppCompatActivity {
needs JavaDoc above this to briefly describe what this class is doing

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/ChangePasswordActivity.java
> +    // Button that sends the user back to the settings screen.
JavaDoc should look like
```
/**
* Button ....
*/
```

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/ChangePasswordActivity.java
> +     */
missing @param

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/SettingsActivity.java
> +    // Button that sends user to change email screen.
JavaDoc should look like
```
/**
* Button ....
*/
```

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/SettingsActivity.java
> +public class SettingsActivity extends AppCompatActivity {
needs JavaDoc above this to briefly describe what this class is doing

2023-08-12 02:43 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/ui/settings/SettingsActivity.java
> +     */
missing @param

2023-08-12 02:46 UTC, jenniferjinyoungyang commented
One more thing, right now, when no email is inputted, it says email is already in use. Can we display message like please enter email if no email is inputted, and email is already in use only for when email is indeed already in use?

2023-08-12 16:03 UTC, jenniferjinyoungyang commented
I will make issues for the comments I made above. Prefer to merge this as we are working off to submit the project soon.

JavaDocs - https://github.com/CSC207-2023Y-UofT/course-project-tindar/issues/138
warning when no email is entered - https://github.com/CSC207-2023Y-UofT/course-project-tindar/issues/137

2023-08-12 16:03 UTC, jenniferjinyoungyang approved these changes

2023-08-12 16:10 UTC, kresimirgotovac approved these changes

2023-08-12 16:13 UTC, navarhontes approved these changes
Thanks for the comments. Like Jennifer said, some javadocs are missing or improperly added and we have made issues for that. I think some logic should be moved out of the UI documents, but we can do that in a different PR. Made #139

2023-08-12 16:13 UTC, merged