created view profile screen and presenter
CSC207-2023Y-UofT/course-project-tindar pull request #42
Opened 2023-07-27 23:26 UTC by candidcalcifer

1/2 of view profile issue

2023-08-02 01:25 UTC, jenniferjinyoungyang commented
Please add Javadocs. If you want to focus on other implementations first, please create a tech debt ticket to finish Javadocs for this feature.

2023-08-02 01:42 UTC, jenniferjinyoungyang requested changes

2023-08-02 01:42 UTC, jenniferjinyoungyang commented on app/src/main/java/com/courseproject/tindar/presenters/viewprofiles/ViewProfilesPresenter.java
> +public class ViewProfilesPresenter {
If you don't need this class, you can delete this file and the folder it belongs to. If you are planning to add something here later, pls add a TODO comment.

2023-08-02 13:20 UTC, navarhontes requested changes
Don't fully understand TextView and MutableLiveData (especially its use in the case of Birthday since Birthday shouldn't change), but I'll defer to you since I don't know how much they care about the quality of frontend code? Other than that, same comments as Jennifer. JavaDocs also makes it easier to give good PR reviews.

2023-08-03 16:46 UTC, jenniferjinyoungyang approved these changes

2023-08-04 01:33 UTC, kresimirgotovac approved these changes

2023-08-04 13:57 UTC, navarhontes approved these changes
Approving because it seems to work and that's the current priority. Made issues out of the remaining problems to be addressed later.

2023-08-04 14:47 UTC, merged